# Use a official Python image
FROM ghcr.io/mlflow/mlflow:v3.8.1

# set working directory
WORKDIR /app

# Install the necessary packages
RUN pip install psycopg2-binary

# Expose the necessary ports
EXPOSE ${MLFLOW_UI_PORT}

# Command to run the MLflow server
CMD ["sh", "-c", "mlflow server --backend-store-uri ${MLFLOW_TRACKING_DB_URI} --host 0.0.0.0 --port ${MLFLOW_UI_PORT} --allowed-hosts \"${MLFLOW_ALLOWED_HOSTS:-mlflow:*,mlflow_app:*,localhost:*,127.0.0.1:*}\""]